### ISSUE TITLE
Graceful logging updates

### ISSUE THREAD

**Issue by justparking** [museumsvictoria/nodel#103]
This issue will continue to include spots where logging could be cleaned up, refined, reworded, etc. It may open and close as situations are identified.

**Comment by justparking** [comment]
`2017-04-05 14:33:35.503 WARN [org.nodel.core.NodelServers.instance0] [channel_server_1] Failure on a channel server; this may be natural. Removing it. (Error was java.net.SocketTimeoutException: Read timed out)`

**Comment by justparking** [comment]
Could indicate to use `-p 0` for "any port" binding.

`org.nodel.io.Unex`pectedIOException: Cannot bind to TCP port 8085; another process must already be bound to the port`

**Comment by justparking** [comment]
```
2017-04-25 10:46:24.343 WARN [org.nodel.threading.ThreadPool] [pool_Discovery_3] An unhandled exception occurred within a thread-pool
java.lang.IllegalArgumentException: port out of range:-1
	at java.net.InetSocketAddress.checkPort(InetSocketAddress.java:143)
	at java.net.InetSocketAddress.<init>(InetSocketAddress.java:185)
	at java.net.DatagramPacket.getSocketAddress(DatagramPacket.java:327)
	at org.nodel.discovery.NodelAdvertiser.processIncomingPacketQueue(NodelAdvertiser.java:288)
	at org.nodel.discovery.NodelAdvertiser.access$0(NodelAdvertiser.java:259)
	at org.nodel.discovery.NodelAdvertiser$1.run(NodelAdvertiser.java:71)
	at org.nodel.threading.ThreadPool.threadMain(ThreadPool.java:303)
	at org.nodel.threading.ThreadPool.access$0(ThreadPool.java:242)
	at org.nodel.threading.ThreadPool$1.run(ThreadPool.java:213)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by justparking** [comment]
When "Content-Type" is missing, NullPointerException in NanoHTTPD.java line 595. Could gracefully handle this.

**Comment by justparking** [comment]
Could suppress stack trace when an interface disappears:
```
2017-09-13 12:30:26.520 WARN [org.nodel.discovery.NodelDiscoverer.192_168_98_115] [pool_Discovery_0] Socket send unexpectedly failed.
java.net.NoRouteToHostException: No route to host: Datagram send failed
        at java.net.TwoStacksPlainDatagramSocketImpl.send(Native Method)
        at java.net.DatagramSocket.send(Unknown Source)
        at org.nodel.discovery.NodelDiscoverer.doSendProbe(NodelDiscoverer.java:305)
        at org.nodel.discovery.NodelDiscoverer.access$300(NodelDiscoverer.java:32)
        at org.nodel.discovery.NodelDiscoverer$3.run(NodelDiscoverer.java:286)
        at org.nodel.threading.ThreadPool.threadMain(ThreadPool.java:303)
        at org.nodel.threading.ThreadPool.access$000(ThreadPool.java:26)
        at org.nodel.threading.ThreadPool$1.run(ThreadPool.java:213)
        at java.lang.Thread.run(Unknown Source)

    (192.168.98.115 interface disappeared)
```

**Comment by justparking** [comment]
Addressed items. Closing for now.
