### ISSUE TITLE
Self generated out-of-band UDP can cripple advertisements

### ISSUE THREAD

**Issue by justparking** [museumsvictoria/nodel#120]
Under certain rare conditions (network and timing), a self-generated UDP "signal" (as opposed to a valid packet) may be generated and then mishandled. This can result in the crippling of the advertisement thread.

Something like this would be logged:
```
[pool_Discovery_2] [org.nodel.threading.ThreadPool] An unhandled exception occurred within a thread-pool
java.lang.IllegalArgumentException: port out of range:-1 
at java.net.InetSocketAddress.checkPort(InetSocketAddress.java:143) 
at java.net.InetSocketAddress.<init>(InetSocketAddress.java:188) 
at java.net.DatagramPacket.getSocketAddress(DatagramPacket.java:330) 
at org.nodel.discovery.NodelAdvertiser.processIncomingPacketQueue(NodelAdvertiser.java:288) 
at org.nodel.discovery.NodelAdvertiser.access$000(NodelAdvertiser.java:36) 
at org.nodel.discovery.NodelAdvertiser$1.run(NodelAdvertiser.java:71) 
at org.nodel.threading.ThreadPool.threadMain(ThreadPool.java:303)
at ... 
```

**Comment by justparking** [comment]
As per code comments, .getSocketAddress() can sneakily throw an exception. This was being used in a safe section of some logging code resulting in the unintended crippling of the advertisement thread.
