### ISSUE TITLE
Race condition affecting toolkit 'Process' on Node recycle

### ISSUE THREAD

**Issue by justparking** [museumsvictoria/nodel#137]
Caught opportunistically today:
```
07-31 15:41:16.09 err: 2018-07-31 15:41:16.094 WARN [org.nodel.jyhost.PyNode_0_Logger] [pool_Nano HTTP_1] saveConfig failed.
07-31 15:41:16.09 err: java.util.ConcurrentModificationException
07-31 15:41:16.09 err: at java.util.HashMap$HashIterator.nextNode(HashMap.java:1442)
07-31 15:41:16.09 err: at java.util.HashMap$KeyIterator.next(HashMap.java:1466)
07-31 15:41:16.09 err: at org.nodel.toolkit.ManagedToolkit.releaseProcesses(ManagedToolkit.java:557)
07-31 15:41:16.09 err: at org.nodel.toolkit.ManagedToolkit.shutdown(ManagedToolkit.java:940)
07-31 15:41:16.09 err: at org.nodel.jyhost.PyNode.cleanupInterpreter(PyNode.java:922)
07-31 15:41:16.09 err: at org.nodel.jyhost.PyNode.applyConfig0(PyNode.java:548)
07-31 15:41:16.09 err: at org.nodel.jyhost.PyNode.access$900(PyNode.java:84)
07-31 15:41:16.09 err: at org.nodel.jyhost.PyNode$8.call(PyNode.java:527)
07-31 15:41:16.09 err: at org.nodel.jyhost.PyNode$8.call(PyNode.java:523)
07-31 15:41:16.09 err: at org.nodel.Threads$2.run(Threads.java:291)
07-31 15:41:16.09 err: at java.lang.Thread.run(Thread.java:748)
07-31 15:41:16.10 err: 2018-07-31 15:41:16.098 WARN [org.nodel.jyhost.NodelHostHTTPD_0] [pool_Nano HTTP_1] Unexpected exception during REST operation.
07-31 15:41:16.10 err: java.util.ConcurrentModificationException
07-31 15:41:16.10 err: at java.util.HashMap$HashIterator.nextNode(HashMap.java:1442)
07-31 15:41:16.10 err: at java.util.HashMap$KeyIterator.next(HashMap.java:1466)
07-31 15:41:16.10 err: at org.nodel.toolkit.ManagedToolkit.releaseProcesses(ManagedToolkit.java:557)
07-31 15:41:16.10 err: at org.nodel.toolkit.ManagedToolkit.shutdown(ManagedToolkit.java:940)
07-31 15:41:16.10 err: at org.nodel.jyhost.PyNode.cleanupInterpreter(PyNode.java:922)
07-31 15:41:16.10 err: at org.nodel.jyhost.PyNode.applyConfig0(PyNode.java:548)
07-31 15:41:16.10 err: at org.nodel.jyhost.PyNode.access$900(PyNode.java:84)
07-31 15:41:16.10 err: at org.nodel.jyhost.PyNode$8.call(PyNode.java:527)
07-31 15:41:16.10 err: at org.nodel.jyhost.PyNode$8.call(PyNode.java:523)
07-31 15:41:16.10 err: at org.nodel.Threads$2.run(Threads.java:291)
```

**Comment by justparking** [comment]
Fixed in commit.
