### ISSUE TITLE
Java 7 unsupported from revision 352+ 

### ISSUE THREAD

**Issue by scroix** [museumsvictoria/nodel#140]
I just noticed this on a machine running Java 7 when I went to update from revision 330 to 379 and backtracked it to 352. I just wanted to flag this as the next official release build will be dropping support for Java 7.

```
java version "1.7.0_45"
Java(TM) SE Runtime Environment (build 1.7.0_45-b18)
Java HotSpot(TM) 64-Bit Server VM (build 24.45-b08, mixed mode)
```
```
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/nodel/jyhost/Launch : Unsupported major.minor version 52.0
ost/Launch : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)
```

**Comment by scroix** [comment]
Java 7 will be eight years old this year. It was removed from public availability in 2015. It's time to move on. The `README.md` has been updated to indicate Java 8 as a requirement.
