### ISSUE TITLE
Bindings error dump on node restart

### ISSUE THREAD

**Issue by justparking** [museumsvictoria/nodel#152]
```
07-08 13:19:59.02 The bindings could not be applied to the Python instance.
java.lang.NullPointerException
	at org.nodel.core.NodelClients.release(NodelClients.java:355)
	at org.nodel.core.NodelClientEvent.close(NodelClientEvent.java:429)
	at org.nodel.host.BaseNode.cleanupBindings(BaseNode.java:782)
	at org.nodel.jyhost.PyNode.applyConfig0(PyNode.java:619)
	at org.nodel.jyhost.PyNode.access$900(PyNode.java:84)
	at org.nodel.jyhost.PyNode$8.call(PyNode.java:527)
	at org.nodel.jyhost.PyNode$8.call(PyNode.java:523)
	at org.nodel.Threads$2.run(Threads.java:291)
	at java.lang.Thread.run(Unknown Source)
07-08 13:19:59.02 (Python and Node script(s) loaded with errors (took 6ms); calling 'main' if present...)
07-08 13:19:59.02 'main' completed with errors - java.lang.ClassCastException: org.python.core.PyNone cannot be cast to org.python.core.PyFunction
```

Possibly continues happily.

**Comment by mcartmel** [comment]
Just a note that it seems to occur most often when editing binding information.

**Comment by mcartmel** [comment]
I'm seeing this happen more and more on certain hosts now.

**Comment by mcartmel** [comment]
@justparking Just to note, this seems to occur when you have a node saved in a binding, but no event or action specified.

**Comment by justparking** [comment]
There is data that was previously santised before handing it over to the nodel server in the previous frontend version that is now no longer sanitised.

A workaround for the moment is to restart the node, OR have make sure either:
1) both node name AND action/event name are cleared
2) both node name and action/event name have data present, even dummy data if necessary.

Fix in progress...

**Comment by justparking** [comment]
An update of this stack-trace:
```
10 15:04:24.06 The bindings could not be applied to the Python instance.
java.lang.NullPointerException
	at org.nodel.core.NodelClients.release(NodelClients.java:475)
	at org.nodel.core.NodelClientAction.close(NodelClientAction.java:270)
	at org.nodel.host.BaseNode.cleanupBindings(BaseNode.java:790)
	at org.nodel.jyhost.PyNode.applyConfig0(PyNode.java:615)
	at org.nodel.jyhost.PyNode.access$900(PyNode.java:84)
	at org.nodel.jyhost.PyNode$8.call(PyNode.java:527)
	at org.nodel.jyhost.PyNode$8.call(PyNode.java:523)
	at org.nodel.Threads$2.run(Threads.java:291)
	at java.lang.Thread.run(Thread.java:748)
11-10 15:04:24.06 (Python and Node script(s) loaded with errors (took 2ms
```

**Comment by justparking** [comment]
Finally got the the bottom of this. Mainly affects Frontend nodes that tend to manipulate large batches of mixed-registered bindings programatiically.
