### ISSUE TITLE
User memory-leak detection

### ISSUE THREAD

**Issue by justparking** [museumsvictoria/nodel#153]
If poor scripting results in unintended memory leak in server, warning or action could be taken?

```
2019-07-08 05:07:07.348 WARN [org.nodel.threading.ThreadPool] [pool_Toolkit_11] An unhandled exception occurred within a thread-pool
java.lang.IllegalStateException: Timer already cancelled.
        at java.util.Timer.sched(Timer.java:397)
        at java.util.Timer.schedule(Timer.java:193)
        at org.nodel.threading.Timers.schedule(Timers.java:96)
        at org.nodel.toolkit.ManagedTimer$1$1.run(ManagedTimer.java:127)
        at org.nodel.threading.ThreadPool.threadMain(ThreadPool.java:303)
        at org.nodel.threading.ThreadPool.access$000(ThreadPool.java:26)
        at org.nodel.threading.ThreadPool$1.run(ThreadPool.java:213)
        at java.lang.Thread.run(Thread.java:748)

Exception in thread "9684SubnetDiscoveryProbeRelay_tcpConnectAndReceive_0" java.lang.OutOfMemoryError: Java heap space
```

**Comment by justparking** [comment]
Or these (as a result of deliberate poor user coding)

```log
...
02-25 02:17:25.26 err: Exception in thread "pool_Nano HTTP_1" java.lang.OutOfMemoryError: Java heap space
02-25 02:17:25.26 err: Exception in thread "pool_Nano HTTP_10" java.lang.OutOfMemoryError: Java heap space
02-25 02:17:25.26 err: Exception in thread "pool_Background_1" java.lang.OutOfMemoryError: Java heap space
02-25 02:17:25.26 err: Exception in thread "pool_Nano HTTP_2" java.lang.OutOfMemoryError: Java heap space
02-25 02:17:25.26 err: Exception in thread "pool_Nano HTTP_8" java.lang.OutOfMemoryError: Java heap space
02-25 02:17:25.26 err: Exception in thread "pool_Nano HTTP_5" java.lang.OutOfMemoryError: Java heap space
02-25 02:17:25.26 err: Exception in thread "pool_Discovery_2" java.lang.OutOfMemoryError: Java heap space
02-25 02:17:25.26 err: Exception in thread "pool_Nano HTTP_13" java.lang.OutOfMemoryError: Java heap space
02-25 02:17:25.26 err: Exception in thread "pool_Nano HTTP_4" java.lang.OutOfMemoryError: Java heap space
02-25 02:17:25.26 err: Exception in thread "pool_Nano HTTP_11" java.lang.OutOfMemoryError: Java heap space
...
```

Could think about have a fallback command, say `sudo reboot now` or `shutdown /r /t 0`.

**Comment by scroix** [comment]
Is there any way to reference and reset the guilty **node** or **nodehost** from within a script itself?

I think about MV for example, where a `sudo reboot now` might be occurring on major server infrastructure and not a lone machine in a gallery.

**Comment by justparking** [comment]
Yes, a system restart would not be something that occurs "straight out of the box".

There are several other options depending on OS and launch environment.

Ideally the process would just shut itself down and its parent would restart it.

Trying to think of the least impactful way using as little config

**Comment by justparking** [comment]
Yes, a system restart would not be something that occurs "straight out of the box".

There are several other options but they depend heavily on theOS and launch environment.

Ideally the process would just shut itself down and its parent would restart it.

Trying to think of the least impactful way using as little config or special installation as possible e.g. avoiding separate watchdog services if possible.

Ideas welcome!

**Comment by scroix** [comment]
Perhaps a **heart-beat?** 💙

The same way we monitor the status in recipes through polling frequent events, such as a network message, or a regular stream on _stdin_.

**If** it does become something larger, then it is a good opportunity to re-consider the case for automating the management of nodehosts, e.g. if one is unavailable, another replica is started in it's place.

It reminds me a little of kubernetes. I wonder if containerization in general would be a possible avenue?
