### ISSUE TITLE
v2.2.1 frontend poorly handles very large list of nodes

### ISSUE THREAD

**Issue by justparking** [museumsvictoria/nodel#168]
When first loading nodel browser list, the browser locks up while it processes the nodes. In my case, >2500 nodes to be listed.

**Comment by justparking** [comment]
Does this also "fix" node selection when updating bindings?

**Comment by justparking** [comment]
I'm not sure the latest commit ([8e1fece4fcd1042e5bf44a83c5f8ecfb31d93faa]) really helped much. In particular, updating bindings is still very poor. A filter on binding names might be a good starting point and make updating very large lists (e.g. Dashboards) a lot easier.

**Comment by scroix** [comment]
I'm not sure if this would play a factor but just the rendering on the browser alone appears to cause some chugging.

Here's an example of a very large activity log measured in pixels.

![Screen Shot 2020-05-26 at 9 45 24 am](https://user-images.githubusercontent.com/9277107/82848294-43a29400-9f36-11ea-8980-4e7321010fc8.png)

**Comment by mcartmel** [comment]
Yes, I've actually created a [fork](https://github.com/mcartmel/nodel) to test a new mechanism for handling nodes with large volumes of activity. Please feel free to test!

**Comment by scroix** [comment]
Oh -- that's awesome. Thank you for pointing it out.

@paxofsnax We should test the dashboard on this build. It's the ultimate test.

**Comment by mcartmel** [comment]
> Oh -- that's awesome. Thank you for pointing it out.
> 
> @paxofsnax We should test the dashboard on this build. It's the ultimate test.

Any feedback on this at all?

**Comment by justparking** [comment]
Technical Nodel interfaces aside, I will state for the record that it's very clear that the "new mechanism" has a noticeable impact on the load time of the Dashboard-type Frontend interfaces (and possibly the update speed after load).

In a test I did on a reasonably large dashboard the "new mechanism" took >16 secs to load fully. Using previous versions it takes <3 secs to load the same large dashboard.

Using the technical Nodel interfaces the "new mechanism" is generally a bit quicker doing some things but it's hard to do a side-by-side comparison because the load behaviour is so different.

Regardless of my last point, I think it would be ideal if the existing Dashboard-type Frontends are excluded from any optimisations made by the "new mechanism". There has never been any issue with their load times and performance. In fact, they've always been impressively fast and efficient and it'd be a shame to lose that.

**Comment by mcartmel** [comment]
I've modified the "new mechanism" to be less aggressive, but retained the reduction in the number of long running operations (which were causing the lack of responsiveness). I also found a more efficient way to buffer the stream of incoming state changes. Load time is significantly improved in my tests.

Please feel free to test and comment further.

**Comment by scroix** [comment]
I'm not sure if the build had issues, but I tried compiling a binary with the new mechanism from here: 

https://github.com/mcartmel/nodel/tree/feature_uispeed

I had some errors immediately after the launch.

```
2020-06-29 10:01:57.075 WARN [org.nodel.jyhost.NodelHostHTTPD_0] [pool_Nano HTTP_2] Unexpected exception during REST operation.
java.lang.NullPointerException
at org.nodel.reflection.Serialisation.serialise(Serialisation.java:698)
at org.nodel.reflection.Serialisation.serialise(Serialisation.java:681)
at org.nodel.reflection.Serialisation.serialise(Serialisation.java:674)
at org.nodel.jyhost.NodelHostHTTPD.serve(NodelHostHTTPD.java:323)
at org.nodel.host.NanoHTTPD$HTTPSession.run(NanoHTTPD.java:634)
at org.nodel.threading.ThreadPool.threadMain(ThreadPool.java:303)
at org.nodel.threading.ThreadPool.access$000(ThreadPool.java:26) 
at org.nodel.threading.ThreadPool$1.run(ThreadPool.java:213)                                       
```

r415 loads the "dashboard" succesfully, albeit slowly (10s).

It might've been an issue with my build? The .jar was missing a revision number.

**Comment by justparking** [comment]
Hey @scroix, I believe that's a different issue. See #152.

**Comment by scroix** [comment]
Thank you.

I've tried the work-around with restarting the node for now, and I've got no errors. However depsite the bindings being wired I'm seeing no activity at all in the logs.

![no-updates](https://user-images.githubusercontent.com/9277107/85962373-b8fcfb00-b9f3-11ea-9326-6b3506dc7b43.jpg)

**Comment by mcartmel** [comment]
You see the 'hold' checkbox is now automatically ticked when larger numbers of actions/events are detected. This prevents the logs from reordering based on time. The process to re-render the list is an intensive task and can cause a decrease in UI responsiveness, so I've changed the default behaviour.

Can you untick 'hold' and check again?

**Comment by mcartmel** [comment]
I also found an issue with the version you were testing, you might want to try again with the latest. @scroix

**Comment by scroix** [comment]
I got around to testing it this morning. I went straight into the deep-end and updated our live server to **r425**. (The venue is closed anyway!).

It's good, **much better**. Here are some not particularly accurate times I recorded to compare when launching the behemoth dashboard.

![dashboard-timed](https://user-images.githubusercontent.com/9277107/86981273-72fd1f80-c1c9-11ea-9207-98e375d94327.png)

**Comment by scroix** [comment]
There was a small UI issue when viewing the interface in 16:9 portrait mode.

![squishy](https://user-images.githubusercontent.com/9277107/86981369-b788bb00-c1c9-11ea-84c5-8608e44cf0e7.png)

**Comment by mcartmel** [comment]
@scroix Thanks for calling out that layout issue. I'll take a look.

**Comment by mcartmel** [comment]
@scroix I've added a fix for the layout issue. Can you please verify? After this I think the issue can be closed.

**Comment by scroix** [comment]
> 
> 
> @scroix I've added a fix for the layout issue. Can you please verify? After this I think the issue can be closed.

It's looking good to me.
