### ISSUE TITLE
@at_cleanup handler should not suppress raised exceptions

### ISSUE THREAD

**Issue by justparking** [museumsvictoria/nodel#174]
This could be dangerous as code failures related to `at_cleanup` might leave the programmer oblivious to any necessary clean up code that was not executing correctly (e.g. and cause resource leaks).

**Comment by justparking** [comment]
Also related, full stack trace not necessary if rapid start stop:

```
Unexpected exception during cleaning up; should be safe to ignore
java.lang.ClassCastException: org.python.core.PyNone cannot be cast to org.python.core.PyFunction
        at org.nodel.jyhost.PyNode.cleanupInterpreter(PyNode.java:909)
        at org.nodel.jyhost.PyNode.close(PyNode.java:1610)
        at org.nodel.jyhost.NodelHost.shutdown(NodelHost.java:530)
        at org.nodel.jyhost.Launch.shutdown(Launch.java:503)
        at org.nodel.jyhost.Launch.main(Launch.java:148)
```

**Comment by justparking** [comment]
This is no a bug per se, but precautionary.
