### ISSUE TITLE
Rename or deletion might fail if Process toolkit function in use

### ISSUE THREAD

**Issue by justparking** [museumsvictoria/nodel#176]
Related exception dump:

```
java.lang.RuntimeException: An attempt was made at removing the node however it still exists. Temporary file locking might be preventing the removal of the node. Try again later.
        at org.nodel.jyhost.PyNode.remove(PyNode.java:1566)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.nodel.rest.REST.resolveRESTcall(REST.java:359)
        at org.nodel.rest.REST.resolveRESTcall(REST.java:34)
        at org.nodel.jyhost.NodelHostHTTPD.serve(NodelHostHTTPD.java:308)
        at org.nodel.host.NanoHTTPD$HTTPSession.run(NanoHTTPD.java:634)
        at org.nodel.threading.ThreadPool.threadMain(ThreadPool.java:303)
        at org.nodel.threading.ThreadPool.access$000(ThreadPool.java:26)
        at org.nodel.threading.ThreadPool$1.run(ThreadPool.java:213)
        at java.lang.Thread.run(Thread.java:748)
```

Ideally any processes would be stopped to allow the operation to succeed.

**Comment by justparking** [comment]
Addressed in upcoming branch.
