### ISSUE TITLE
Error suppression on 

### ISSUE THREAD

**Issue by justparking** [museumsvictoria/nodel#288]
This occurred during a node restart:

    Remote event handling failed - java.lang.IllegalStateException: Event handling failure (internal server error) - 'remote_event_IPAddress'-

Remote event handler error feedback could be suppressed if the toolkit is being shutdown or already shutdown.

**Comment by justparking** [comment]
The same applies to active HTTP calls - they can fail silently too.

Or anything that's done via the toolkit.

And if not entirely suppressed, dumping an entire stack trace can be avoided.

**Comment by justparking** [comment]
The same should apply to action, emit and call handlers, e.g. after a recycle this might happen where the error is simply because the node it restarting.

```log
05-24 09:23:38.36 (action) Traceback (most recent call last):
05-24 09:23:38.37   File "/opt/nodel/./nodes/Frontend/ingredient_echo.py", line 7, in EchoRequest
05-24 09:23:38.37     local_event_EchoReply.emit(arg)
05-24 09:23:38.37 AttributeError: 'dict' object has no attribute 'emit'
```

**Comment by justparking** [comment]
Might be related too, this ended up in the global log:

```
02-06 11:04:49.53 [org.nodel.jyhost.PyNode_19_MSUPPRESSEDOfficeTouchpanel] Python interpreter function resolution failed when it should not have. name:'remote_event_GroupStatus', class:class org.python.core.PyNone value:None
02-06 11:04:49.53 [org.nodel.threading.ThreadPoolFence] An unhandled exception occurred within a thread-pool
java.lang.RuntimeException: Event handler
	at org.nodel.core.NodelClientEvent$3.run(NodelClientEvent.java:337)
	at org.nodel.threading.ThreadPoolFence$1.run(ThreadPoolFence.java:67)
	at org.nodel.threading.GrowingThreadPool.threadMain(GrowingThreadPool.java:315)
	at org.nodel.threading.GrowingThreadPool.access$000(GrowingThreadPool.java:24)
	at org.nodel.threading.GrowingThreadPool$1.run(GrowingThreadPool.java:221)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.RuntimeException: java.lang.IllegalStateException: Event handling failure (internal server error) - 'remote_event_GroupStatus'
	at org.nodel.jyhost.PyNode.handleRemoteEventArrival(PyNode.java:1368)
	at org.nodel.jyhost.PyNode.access$2900(PyNode.java:83)
	at org.nodel.jyhost.PyNode$15.handleEvent(PyNode.java:1293)
	at org.nodel.core.NodelClientEvent$2.handleEvent(NodelClientEvent.java:308)
	at org.nodel.core.NodelClientEvent$3.run(NodelClientEvent.java:334)
	... 5 more
Caused by: java.lang.IllegalStateException: Event handling failure (internal server error) - 'remote_event_GroupStatus'
	at org.nodel.jyhost.PyNode.handleRemoteEventArrival(PyNode.java:1351)
	... 9 more
```
