### ISSUE TITLE
Background event arg persistence does not always occur

### ISSUE THREAD

**Issue by justparking** [museumsvictoria/nodel#76]
Have seen this occasionally where the states (local and remote) are not always persisted.

**Comment by justparking** [comment]
Related logs:
```
16-12-15 16:35:34 [nodeloneoff_91] [org.nodel.jyhost.PyNode_5_XXXX] The bindings could not be applied to the Python instance.
    java.lang.NullPointerException
    	at org.nodel.core.NodelClients.release(NodelClients.java:348)
    	at org.nodel.core.NodelClientEvent.close(NodelClientEvent.java:324)
    	at org.nodel.host.BaseNode.cleanupBindings(BaseNode.java:779)
    	at org.nodel.jyhost.PyNode.applyConfig0(PyNode.java:600)
    	at org.nodel.jyhost.PyNode.access$900(PyNode.java:82)
    	at org.nodel.jyhost.PyNode$8.call(PyNode.java:512)
    	at org.nodel.jyhost.PyNode$8.call(PyNode.java:508)
    	at org.nodel.Threads$2.run(Threads.java:291)
    	at java.lang.Thread.run(Thread.java:745)
```

**Comment by justparking** [comment]
Resolved in above commit.
